### ISSUE TITLE
MMF not working

### ISSUE THREAD

**Issue by augustocvieira** [bogus-things/RG_ActionPatches#11]
The option shows up onscreen but nothing happens once I click on it, do you plan on updating any time soon? If not I have knowledge in .NET and could perhaps try my hand at figuring this out, I have cloned your repo and mapped the BeepinEx assemblies but Visual Studio still won't compile the Solution, it gives the following error:
<img width="643" alt="image" src="https://github.com/bogus-things/RG_ActionPatches/assets/12091345/15b165a8-9182-41c5-a5c0-a0a4ac8aba01">

**Comment by bogus-things** [comment]
Thanks for the report! I've got a fix for this -- basically some generated function names changed with the expansion release, so I had to do the process Hawk outlined [in this doc](https://github.com/bogus-things/RG_ActionPatches/blob/develop/How%20to%20add%20commands%20in%20RG.md) over again.

I'm planning to release a version with fixes for this and some other reported bugs hopefully by next week or so. I had been delaying to try and work out some stuff with the new expansion features, but those are seeming like a dead end at this point

**Comment by bogus-things** [comment]
Alright I've got a fix for this in [the latest release](https://github.com/bogus-things/RG_ActionPatches/releases/tag/2.0.0), so I'll go ahead and close this out. But feel free to create another issue if you see any more weirdness related to this. Thanks again!
